<script setup>
import { ref } from 'vue'
const menu = [{ icon: '◷', title: '骑行记录', copy: '查看每一次绿色出行' }, { icon: '♧', title: '碳积分', copy: '680 分可用' }, { icon: '◈', title: '车辆服务', copy: '保养、故障与客服' }, { icon: '⚙', title: '设置', copy: '隐私与账号安全' }]
const showCode = ref(false)
function clickMenu(item) { uni.showToast({ title: `${item.title}功能已进入开发排期`, icon: 'none' }) }
</script>

<template>
  <view class="page profile"><view class="profile-head"><view class="avatar">途</view><view><b>绿色骑行者</b><text>已加入途能 28 天</text></view><text>›</text></view><view class="stats"><view><b>12.6</b><text>本月里程 km</text></view><view><b>680</b><text>碳积分</text></view><view><b>8.4</b><text>减碳 kg</text></view></view><view class="member"><view><text>途能绿卡会员</text><b>再骑行 3 次升级为银卡</b></view><button @click="showCode = true">会员码</button></view><view class="menu"><view v-for="item in menu" :key="item.title" @click="clickMenu(item)"><text class="icon">{{ item.icon }}</text><view><b>{{ item.title }}</b><text>{{ item.copy }}</text></view><text class="arrow">›</text></view></view><view v-if="showCode" class="mask" @click="showCode = false"><view class="code" @click.stop><text>我的会员码</text><view class="qr">▦</view><b>绿色骑行者</b><text>出示会员码，解锁专属权益</text></view></view></view>
</template>

<style scoped lang="scss">
.profile{min-height:100vh;padding:34rpx 28rpx;background:#f4f8f1}.profile-head{display:flex;align-items:center;padding:35rpx 27rpx;border-radius:20rpx 20rpx 0 0;background:linear-gradient(135deg,#1c6742,#3b9c62);color:#fff}.avatar{display:grid;width:88rpx;height:88rpx;margin-right:21rpx;place-items:center;border-radius:50%;background:#d8efcf;color:#27824c;font-size:38rpx;font-weight:700}.profile-head>view:nth-child(2){flex:1}.profile-head b,.profile-head text{display:block}.profile-head b{font-size:33rpx}.profile-head text{margin-top:9rpx;color:#cfebd5;font-size:21rpx}.profile-head>text{font-size:38rpx}.stats{display:grid;grid-template-columns:repeat(3,1fr);padding:26rpx 0;border-radius:0 0 20rpx 20rpx;background:#fff;text-align:center}.stats b,.stats text{display:block}.stats b{font-size:34rpx;color:#237a48}.stats text{margin-top:8rpx;color:#839084;font-size:19rpx}.member{display:flex;align-items:center;justify-content:space-between;margin-top:24rpx;padding:26rpx;border-radius:16rpx;background:#f2df9e}.member text,.member b{display:block}.member text{font-size:25rpx;color:#684e10}.member b{margin-top:9rpx;color:#8b6c1c;font-size:20rpx}.member button{width:120rpx;margin:0;border-radius:20rpx;background:#6f5717;color:#fff;font-size:21rpx;line-height:55rpx}.menu{overflow:hidden;margin-top:24rpx;border-radius:16rpx;background:#fff}.menu>view{display:flex;align-items:center;padding:23rpx;border-bottom:1rpx solid #edf1eb}.menu>view:last-child{border:0}.icon{width:58rpx;color:#278b50;font-size:35rpx}.menu>view>view{flex:1}.menu b,.menu text{display:block}.menu b{font-size:26rpx}.menu>view>view text{margin-top:7rpx;color:#899389;font-size:19rpx}.arrow{font-size:36rpx;color:#9dab9e}.mask{position:fixed;z-index:8;inset:0;display:grid;place-items:center;background:rgba(15,45,27,.55)}.code{width:530rpx;padding:45rpx;border-radius:22rpx;background:#fff;text-align:center}.code>text,.code>b{display:block}.code>text{color:#748274;font-size:22rpx}.code .qr{margin:27rpx auto;color:#278d51;font-size:160rpx;line-height:1}.code b{font-size:30rpx}.code>b+text{margin-top:13rpx;font-size:20rpx}
</style>
