<script setup>
import { onMounted, ref } from 'vue'
import { Search, Refresh, View, Check, Close, Lock, Unlock, Edit, Download } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi } from '../services/admin-api'

const rows = ref([]); const loading = ref(false); const keyword = ref(''); const status = ref(''); const detail = ref(null); const editVisible = ref(false); const editForm = ref({})
const load = async () => { loading.value = true; try { const result = await adminApi.merchants({ keyword: keyword.value || undefined, status: status.value || undefined }); rows.value = result.items || [] } catch (error) { ElMessage.error(error.message) } finally { loading.value = false } }
const update = async (row, nextStatus) => { try { if (nextStatus === 'rejected') await ElMessageBox.confirm(`驳回“${row.name}”的入驻申请？`, '确认审核', { type: 'warning' }); await adminApi.updateMerchant(row.merchant_id, { status: nextStatus }); ElMessage.success('商家状态已更新'); load() } catch (error) { if (!['cancel', 'close'].includes(error)) ElMessage.error(error.message) } }
const openEdit = (row) => { editForm.value = { ...row }; editVisible.value = true }
const saveEdit = async () => { try { await adminApi.updateMerchant(editForm.value.merchant_id, { name: editForm.value.name, merchantType: editForm.value.merchant_type, contactName: editForm.value.contact_name, contactPhone: editForm.value.contact_phone, cooperationSummary: editForm.value.cooperation_summary }); ElMessage.success('商家信息已保存'); editVisible.value = false; load() } catch (error) { ElMessage.error(error.message) } }
onMounted(load)
</script>

<template>
  <section class="page-head"><div><h1>商家管理</h1><p>管理经销商、景区和高校运营商的入驻审核与合作状态。</p></div><div class="head-actions"><el-button :icon="Download" @click="ElMessage.info('商家列表可从浏览器导出')">导出列表</el-button><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button></div></section>
  <el-card shadow="never"><div class="table-toolbar"><div class="filter-row"><el-input v-model="keyword" :prefix-icon="Search" placeholder="搜索商家名称 / 联系人" clearable @keyup.enter="load" /><el-select v-model="status" placeholder="全部状态" clearable @change="load"><el-option label="正常" value="active" /><el-option label="待审核" value="pending" /><el-option label="冻结" value="frozen" /><el-option label="已驳回" value="rejected" /></el-select></div><span>共 {{ rows.length }} 家商家</span></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="name" label="商家名称" min-width="180" /><el-table-column prop="merchant_type" label="类型" width="120"><template #default="scope">{{ {dealer: '经销商', scenic: '景区', campus: '高校'}[scope.row.merchant_type] || scope.row.merchant_type }}</template></el-table-column><el-table-column prop="contact_name" label="联系人" width="110" /><el-table-column prop="contact_phone" label="联系电话" width="140" /><el-table-column prop="created_at" label="入驻时间" min-width="170" /><el-table-column prop="status" label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.status === 'active' ? 'success' : scope.row.status === 'pending' ? 'warning' : 'danger'">{{ {active: '正常', pending: '待审核', frozen: '冻结', rejected: '已驳回'}[scope.row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" min-width="300" fixed="right"><template #default="scope"><el-button link type="primary" :icon="View" @click="detail = scope.row">详情</el-button><el-button link type="primary" :icon="Edit" @click="openEdit(scope.row)">编辑</el-button><template v-if="scope.row.status === 'pending'"><el-button link type="success" :icon="Check" @click="update(scope.row, 'active')">通过</el-button><el-button link type="danger" :icon="Close" @click="update(scope.row, 'rejected')">驳回</el-button></template><template v-else><el-button link :type="scope.row.status === 'frozen' ? 'success' : 'danger'" :icon="scope.row.status === 'frozen' ? Unlock : Lock" @click="update(scope.row, scope.row.status === 'frozen' ? 'active' : 'frozen')">{{ scope.row.status === 'frozen' ? '解冻' : '冻结' }}</el-button></template></template></el-table-column></el-table></el-card>
  <el-drawer v-model="detail" title="商家详情" size="430px"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="商家名称">{{ detail.name }}</el-descriptions-item><el-descriptions-item label="类型">{{ detail.merchant_type }}</el-descriptions-item><el-descriptions-item label="联系人">{{ detail.contact_name }}</el-descriptions-item><el-descriptions-item label="联系电话">{{ detail.contact_phone }}</el-descriptions-item><el-descriptions-item label="合作记录">{{ detail.cooperation_summary || '暂无合作记录' }}</el-descriptions-item></el-descriptions></el-drawer>
  <el-dialog v-model="editVisible" title="编辑商家信息" width="460px"><el-form label-position="top"><el-form-item label="商家名称"><el-input v-model="editForm.name" /></el-form-item><el-form-item label="商家类型"><el-select v-model="editForm.merchant_type" style="width: 100%"><el-option label="经销商" value="dealer" /><el-option label="景区" value="scenic" /><el-option label="高校运营商" value="campus" /></el-select></el-form-item><el-form-item label="联系人"><el-input v-model="editForm.contact_name" /></el-form-item><el-form-item label="联系电话"><el-input v-model="editForm.contact_phone" /></el-form-item><el-form-item label="合作记录"><el-input v-model="editForm.cooperation_summary" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="editVisible = false">取消</el-button><el-button type="primary" @click="saveEdit">保存</el-button></template></el-dialog>
</template>
